### ISSUE TITLE
Does not appear to work for .Net Framework [4.8] C#

### ISSUE THREAD

**Issue by davidcorbin-atmosera** [KirillOsenkov/LargeAddressAware#14]
1)Added package (verified .csproj file has targets]. 
2)Added the Property Group (no qualifiers) to .csproj file [using VS-2019]

Build, and DumpBin does not indicate that the bit is set in the header...

Before digging deeper, want to confirm that this should be a working scenario....

**Comment by KirillOsenkov** [comment]
Can you build using /bl (https://msbuildlog.com) and search the binlog for LargeAddressAware? Curious if the task is even running.
Also see if something else overwrites the exe at a later stage in the build.

**Comment by davidcorbin-atmosera** [comment]
Thanks for the prompt response. Was not able to get /bl to work with VS-2022 [and .sln fails when invoked from msbuild command line].....

But I was able to turn up the logging in VS, and capture the line which seems relevant:
`6>Target "SetLargeAddressAware" skipped, due to false condition; (('$(DesignTimeBuild)' != 'true' And '$(BuildingProject)' == 'true') And '$(LargeAddressAware)' == 'true' And Exists('$(LargeAddressAwareAssemblyFile)') And Exists('$(LargeAddressAwareTargetAssembly)') And ('$(OutputType)' == 'Exe' Or '$(OutputType)' == 'Winexe')) was evaluated as (('' != 'true' And 'true' == 'true') And '' == 'true' And Exists('G:\repos\bitbucket\ehrmonitoring - QuickDumpPatch\NextGen.Tooling.MemoryEvaluation\packages\LargeAddressAware.1.0.6\build\net46\SetLargeAddressAware.dll') And Exists('obj\x86\Debug\NextGen.MemoryAnalyzer.AquisitionConsole.exe') And ('Exe' == 'Exe' Or 'Exe' == 'Winexe')).
`
Still trying to determine which of the "and" clauses is false....

At least your response seems to indicate that it is expected to work with 4.8 (full Framework)_ and is not something specific to "Core" [aka 5.0 thru 7.0]

**Comment by davidcorbin-atmosera** [comment]
In the words of Emily Latella "Nevermind!"....

Turns out I was running "dumpbin /headers" on the "bin/debug" directory, but had actually updted to build x86 specific into the "bin/x86/debug" folder.... Works as expected.

**Comment by KirillOsenkov** [comment]
Yes, binlog support is hard to get right with VS 2022, but it should be easy from the command line. 

Did you mean that your solution fails when you try to build it from command line using `msbuild /r /bl YourSolution.sln`? 

From your false condition I can see that it evaluated `'$(LargeAddressAware)' == 'true'` as `'' == 'true'`, so that's the failing condition. This means you hadn't set the LargeAddressAware property correctly, or at least it didn't see it.

I recommend you try getting the binlog working properly and spend some time just looking around to understand what is going on, it's a useful tool when dealing with MSBuild :)

Glad you sorted it out.
